'use client';

import { WalletButton } from '../solana/solana-provider';
import * as React from 'react';
import { ReactNode, Suspense, useEffect, useRef } from 'react';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

import { AccountChecker } from '../account/account-ui';
import {
  ClusterChecker,
  ClusterUiSelect,
  ExplorerLink,
} from '../cluster/cluster-ui';
import toast, { Toaster } from 'react-hot-toast';

import GigenticFrontendFeature from '@/components/gigentic-frontend/gigentic-frontend-feature';

import GigenticDemoBlue from '@/components/gigentic-frontend/demo-blue';
import GigenticDemo from '@/components/gigentic-frontend/gigentic-demo';
import SearchAgent from '../search-agent/search-agent';
import GigenticInterface from '../gigentic-frontend/gigentic-interface';
import { ThemeProvider } from '@/components/theme-provider';
export function UiLayout({
  children,
  links,
}: {
  children: ReactNode;
  links: { label: string; path: string }[];
}) {
  const pathname = usePathname();

  return (
    <div>
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        // defaultTheme="dark"
        // defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <GigenticInterface />
      </ThemeProvider>
    </div>

    // <div>
    //   <div className="flex-1">
    //     <Link className="" href="/">
    //       <img className="md:h-40" alt="Logo" src="/logo.png" />
    //     </Link>
    //   </div>
    //   <div className="flex-1">
    //     <ul className="">
    //       {links.map(({ label, path }) => (
    //         <li key={path}>
    //           <Link
    //             className={pathname.startsWith(path) ? 'active' : ''}
    //             href={path}
    //           >
    //             {label}
    //           </Link>
    //         </li>
    //       ))}
    //     </ul>
    //   </div>

    //   <div className="flex-none space-x-2">
    //     <WalletButton />
    //     <ClusterUiSelect />
    //   </div>

    //   {/* <div className="flex-1">
    //     <SearchAgent />
    //   </div> */}
    //   {/* <GigenticFrontendFeature /> */}
    //   {/* <GigenticDemoBlue /> */}
    //   {/* <GigenticDemo /> */}
    //   <div className="flex-grow w-full mx-4 lg:mx-auto">
    //     <Suspense
    //       fallback={
    //         <div className="text-center my-32">
    //           <span className="loading loading-spinner loading-lg">
    //             Loading...
    //           </span>
    //         </div>
    //       }
    //     >
    //       {children}
    //     </Suspense>
    //     <Toaster position="bottom-right" />
    //   </div>

    //   <footer className="">
    //     <aside>
    //       <p>
    //         Generated by{' '}
    //         <a
    //           className="link"
    //           href=""
    //           target="_blank"
    //           rel="noopener noreferrer"
    //         >
    //           Gigentic
    //         </a>
    //       </p>
    //     </aside>
    //   </footer>
    // </div>
  );
}

export function AppModal({
  children,
  title,
  hide,
  show,
  submit,
  submitDisabled,
  submitLabel,
}: {
  children: ReactNode;
  title: string;
  hide: () => void;
  show: boolean;
  submit?: () => void;
  submitDisabled?: boolean;
  submitLabel?: string;
}) {
  const dialogRef = useRef<HTMLDialogElement | null>(null);

  useEffect(() => {
    if (!dialogRef.current) return;
    if (show) {
      dialogRef.current.showModal();
    } else {
      dialogRef.current.close();
    }
  }, [show, dialogRef]);

  return (
    <dialog className="modal" ref={dialogRef}>
      <div className="modal-box space-y-5">
        <h3 className="font-bold text-lg">{title}</h3>
        {children}
        <div className="modal-action">
          <div className="join space-x-2">
            {submit ? (
              <button
                className="btn btn-xs lg:btn-md btn-primary"
                onClick={submit}
                disabled={submitDisabled}
              >
                {submitLabel || 'Save'}
              </button>
            ) : null}
            <button onClick={hide} className="btn">
              Close
            </button>
          </div>
        </div>
      </div>
    </dialog>
  );
}

export function AppHero({
  children,
  title,
  subtitle,
}: {
  children?: ReactNode;
  title: ReactNode;
  subtitle: ReactNode;
}) {
  return (
    <div className="hero py-[64px]">
      <div className="hero-content text-center">
        <div className="max-w-2xl">
          {typeof title === 'string' ? (
            <h1 className="text-5xl font-bold">{title}</h1>
          ) : (
            title
          )}
          {typeof subtitle === 'string' ? (
            <p className="py-6">{subtitle}</p>
          ) : (
            subtitle
          )}
          {children}
        </div>
      </div>
    </div>
  );
}

export function ellipsify(str = '', len = 4) {
  if (str.length > 30) {
    return (
      str.substring(0, len) + '..' + str.substring(str.length - len, str.length)
    );
  }
  return str;
}

export function useTransactionToast() {
  return (signature: string) => {
    toast.success(
      <div className={'text-center'}>
        <div className="text-lg">Transaction sent</div>
        <ExplorerLink
          path={`tx/${signature}`}
          label={'View Transaction'}
          className="btn btn-xs btn-primary"
        />
      </div>,
    );
  };
}
