[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gigentic_frontend = "6TWkDYVxEiiyVPgX6eg3Rd3N845sPFpWYiUXeneoZXau"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
lint = "cargo dylint --all --workspace"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/gigentic-frontend.spec.ts"
