[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gigentic = "J2UENgBQrdJFy2NcFbBsxyHHdi4CZVuBg5FXmbYxfu4"

[programs.localnet]
gigentic = "J2UENgBQrdJFy2NcFbBsxyHHdi4CZVuBg5FXmbYxfu4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
deploy-registry = "yarn run ts-node admin/deploy-registry.ts"
lint = "cargo dylint --all --workspace"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/gigentic.spec.ts"
write-services = "yarn run ts-node admin/write-services.ts"
