[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gigentic = "2xtwCiDhiQ9vuTFpR3wECJaHyvtE7L9pBPbNHdnsk1YS"

[programs.testnet]
gigentic = "2xtwCiDhiQ9vuTFpR3wECJaHyvtE7L9pBPbNHdnsk1YS"

[programs.localnet]
gigentic = "2xtwCiDhiQ9vuTFpR3wECJaHyvtE7L9pBPbNHdnsk1YS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "https://rpc.testnet.soo.network/rpc"
wallet = "~/.config/solana/id.json"

[scripts]
deploy-registry = "yarn run ts-node admin/deploy-registry.ts"
lint = "cargo dylint --all --workspace"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/gigentic.spec.ts"
write-services = "yarn run ts-node admin/write-services.ts"
