[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gigentic = "7nNajkF7T3zgYRT9vMDZc8esjuPubUf5m3s31jeh1HEY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
create-service = "yarn run ts-node admin/create-service.ts"
deploy-registry = "yarn run ts-node admin/deploy-registry.ts"
lint = "cargo dylint --all --workspace"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/gigentic.spec.ts"
