[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gigentic = "7JynKYjRNQq3JH6XEGzHLuKtkyWe9yh52KiArwQjxUKz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
lint = "cargo dylint --all --workspace"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/gigentic.spec.ts"
deploy-registry = "yarn run ts-node admin/deploy-registry.ts"
