name: main

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: .

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: "1.79.0"
  SOLANA_CLI_VERSION: "1.18.18"

jobs:
  fmt-clippy:
    name: fmt & clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Cache build files
        uses: Swatinem/rust-cache@v2
      - name: Cargo fmt
        run: cargo fmt -- --check
      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          profile: minimal
          override: true
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v1
      - name: Run package checks
        run: cargo check
      - name: Run unit tests
        run: cargo test --lib

  yarn-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install yarn
        run: yarn
      - name: Run prettier
        run: yarn prettier . --check

  yarn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install yarn
        run: yarn
      - name: Run lint
        run: yarn lint

  anchor-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          profile: minimal
          override: true
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: "true"
      - uses: ./.github/actions/setup-solana/
      - name: install anchor cli
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli --locked
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Setup yarn
        run: npm install -g yarn
      - name: Install yarn
        run: yarn
      - name: install typescript
        run: npm install typescript -g
      - name: install mocha
        run: |
          npm install ts-mocha -g
          npm install --global mocha
      - name: run anchor tests
        run: anchor test
